name: Deploy Amtec Chatbot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install
    - run: npm test
    - name: Start server
      run: |
        nohup node server.js > server.log 2>&1 &
        echo $! > server.pid
    - name: Verify deployment
      run: |
        sleep 5
        curl -f http://localhost:3000/health || exit 1
